const mongoose = require('mongoose');

const taskSchema = new mongoose.Schema({
  tenantId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Tenant',
    required: true,
    index: true,
  },
  projectId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Project',
    required: true,
    index: true,
  },
  title: {
    type: String,
    required: [true, 'Task title is required'],
    trim: true,
    maxlength: [200, 'Title cannot exceed 200 characters'],
  },
  description: {
    type: String,
    trim: true,
    default: '',
  },
  status: {
    type: String,
    enum: ['todo', 'in_progress', 'review', 'done'],
    default: 'todo',
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent'],
    default: 'medium',
  },
  assignee: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null,
  },
  createdBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  dueDate: {
    type: Date,
    default: null,
  },
  aiSuggestedDueDate: {
    // AI-generated deadline prediction
    type: Date,
    default: null,
  },
  completedAt: {
    type: Date,
    default: null,
  },
  order: {
    // For drag-and-drop ordering within a status column
    type: Number,
    default: 0,
  },
  tags: [{
    type: String,
    trim: true,
  }],
  isAIGenerated: {
    // True if this task was generated by AI breakdown
    type: Boolean,
    default: false,
  },
  parentTask: {
    // For AI-generated subtasks, reference to parent
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Task',
    default: null,
  },
}, { timestamps: true });

// When task is marked done, set completedAt
taskSchema.pre('save', function () {
  if (this.isModified('status') && this.status === 'done' && !this.completedAt) {
    this.completedAt = new Date();
  }

  if (this.isModified('status') && this.status !== 'done') {
    this.completedAt = null;
  }
});
module.exports = mongoose.model('Task', taskSchema);